spring:
  datasource:
    url: jdbc:mysql://esg-goals.c5laoqw4cyin.us-east-1.rds.amazonaws.com:3306/card_management_db
    username: admin
    password: sB6mbtzNHmCQI4eN4yLo
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  level:
    root: info
    sql: info
    web: info
